--- 
apiVersion: v1
kind: Service
metadata:
  name: sampleapp
  namespace: argocd
  labels:
    app: sampleapp
  namespace: test-dev-app
spec:
  ports:
   - port: 80
     name: http
     targetPort: 8080
  selector:
   app: sampleapp